<?php

declare(strict_types=1);
require_once __DIR__ . '/../../config/app.php'; require_once __DIR__ . '/../../config/database.php'; require_once __DIR__ . '/../../includes/functions.php'; require_once __DIR__ . '/../../includes/auth.php'; require_role(['system_admin']); $user = current_user(); $flash = flash_message();
$summary = $pdo->query("SELECT (SELECT COUNT(*) FROM users) AS total_users,(SELECT COUNT(*) FROM courses) AS total_courses,(SELECT COUNT(*) FROM batches) AS total_batches,(SELECT COUNT(*) FROM enrollments) AS total_enrollments,(SELECT COUNT(*) FROM sessions WHERE is_unlocked = 1) AS unlocked_sessions,(SELECT COUNT(*) FROM watched_sessions) AS watched_records")->fetch() ?: [];
$roleBreakdown = $pdo->query("SELECT roles.name, COUNT(*) AS total FROM users INNER JOIN roles ON roles.id = users.role_id GROUP BY roles.name ORDER BY total DESC")->fetchAll();
$courseProgress = $pdo->query("SELECT courses.title, COUNT(DISTINCT enrollments.student_id) AS students, COUNT(DISTINCT sessions.id) AS sessions, SUM(CASE WHEN sessions.is_unlocked = 1 THEN 1 ELSE 0 END) AS unlocked_sessions FROM courses LEFT JOIN enrollments ON enrollments.course_id = courses.id AND enrollments.status = 'active' LEFT JOIN units ON units.course_id = courses.id LEFT JOIN topics ON topics.unit_id = units.id LEFT JOIN sessions ON sessions.topic_id = topics.id GROUP BY courses.id, courses.title ORDER BY courses.title ASC")->fetchAll();
$watchProgress = $pdo->query("SELECT users.first_name, users.last_name, courses.title AS course_title, COUNT(DISTINCT watched_sessions.session_id) AS watched_count, COALESCE(AVG(watched_sessions.progress_percent), 0) AS avg_progress FROM watched_sessions INNER JOIN users ON users.id = watched_sessions.student_id INNER JOIN sessions ON sessions.id = watched_sessions.session_id INNER JOIN topics ON topics.id = sessions.topic_id INNER JOIN units ON units.id = topics.unit_id INNER JOIN courses ON courses.id = units.course_id GROUP BY users.id, courses.id ORDER BY avg_progress DESC")->fetchAll();
$pageTitle = 'Analytics - ' . APP_NAME; $pageHeading = 'Basic Analytics'; $pageDescription = 'View core counts, role distribution, course readiness, and student watch progress across the Hybrid Learning Hub.'; require_once __DIR__ . '/../../includes/layouts/admin_header.php';
?>
<div class="row g-4 mb-4"><div class="col-sm-6 col-xl-2"><div class="surface-card metric-card"><div class="metric-label">Users</div><div class="metric-value"><?php echo e((string) ($summary['total_users'] ?? 0)); ?></div></div></div><div class="col-sm-6 col-xl-2"><div class="surface-card metric-card"><div class="metric-label">Courses</div><div class="metric-value"><?php echo e((string) ($summary['total_courses'] ?? 0)); ?></div></div></div><div class="col-sm-6 col-xl-2"><div class="surface-card metric-card"><div class="metric-label">Batches</div><div class="metric-value"><?php echo e((string) ($summary['total_batches'] ?? 0)); ?></div></div></div><div class="col-sm-6 col-xl-2"><div class="surface-card metric-card"><div class="metric-label">Enrollments</div><div class="metric-value"><?php echo e((string) ($summary['total_enrollments'] ?? 0)); ?></div></div></div><div class="col-sm-6 col-xl-2"><div class="surface-card metric-card"><div class="metric-label">Unlocked Sessions</div><div class="metric-value"><?php echo e((string) ($summary['unlocked_sessions'] ?? 0)); ?></div></div></div><div class="col-sm-6 col-xl-2"><div class="surface-card metric-card"><div class="metric-label">Watch Logs</div><div class="metric-value"><?php echo e((string) ($summary['watched_records'] ?? 0)); ?></div></div></div></div>
<div class="row g-4"><div class="col-xl-4"><div class="surface-card table-card p-4 h-100"><h2 class="h5 mb-3">Role Distribution</h2><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Role</th><th>Total</th></tr></thead><tbody><?php foreach ($roleBreakdown as $row): ?><tr><td><?php echo e(role_label($row['name'])); ?></td><td><?php echo e((string) $row['total']); ?></td></tr><?php endforeach; ?></tbody></table></div></div></div><div class="col-xl-8"><div class="surface-card table-card p-4 h-100"><h2 class="h5 mb-3">Course Readiness</h2><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Course</th><th>Students</th><th>Sessions</th><th>Unlocked</th></tr></thead><tbody><?php foreach ($courseProgress as $row): ?><tr><td><?php echo e($row['title']); ?></td><td><?php echo e((string) ($row['students'] ?? 0)); ?></td><td><?php echo e((string) ($row['sessions'] ?? 0)); ?></td><td><?php echo e((string) ($row['unlocked_sessions'] ?? 0)); ?></td></tr><?php endforeach; ?></tbody></table></div></div></div></div>
<div class="row g-4 mt-1"><div class="col-12"><div class="surface-card table-card p-4"><h2 class="h5 mb-3">Student Watch Progress</h2><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Student</th><th>Course</th><th>Watched Sessions</th><th>Average Progress</th></tr></thead><tbody><?php foreach ($watchProgress as $row): ?><tr><td><?php echo e(trim($row['first_name'] . ' ' . $row['last_name'])); ?></td><td><?php echo e($row['course_title']); ?></td><td><?php echo e((string) $row['watched_count']); ?></td><td><?php echo e((string) round((float) $row['avg_progress'])); ?>%</td></tr><?php endforeach; ?></tbody></table></div></div></div></div>
<?php require_once __DIR__ . '/../../includes/layouts/admin_footer.php'; ?>
